In [1]:
import numpy as np
import pandas as pd

In [2]:
inc_df = pd.read_csv('inc_data.csv', sep='|')

In [3]:
inc_df.head(10)

,Rank_2017,Company_Name,Revenue_2016,Industry,Employees,Founded,Growth_3_yrs,Brief_Desc,Leadership,City,State,Website,Description
0,1,Skillz,$54.2 M,Software,58.0,2012.0,"50,059%",Has developed a mobile platform that enables u...,Andrew Paradise,San Francisco,CA,skillz.com,Americaâ€™s fastest-growing company is the e-spo...
1,2,EnviroSolar Power,$37.4 M,Energy,85.0,2012.0,"36,065%","Provides homeowners and businesses with solar,...",Abraham Issa,Fort Worth,TX,envirosolarpower.com,EnviroSolar Power installs and manages solar e...
2,3,Gametime,$48.8 M,Consumer Products & Services,75.0,2013.0,"34,021%",A mobile marketplace for last-minute tickets t...,Brad Griffith,San Francisco,CA,gametime.co,Brad Griffith came up with the idea for Gameti...
3,4,Club Pilates Franchise,$26.8 M,Consumer Products & Services,31.0,2007.0,"21,319%",Franchises hundreds of Pilates studios worldwi...,Anthony Geisler,Costa Mesa,CA,clubpilates.com,Club Pilates Franchise is bulking up. The fitn...
4,5,Halo Top Creamery,$49.1 M,Food & Beverage,10.0,2012.0,"20,944%","Makes all-natural, low-calorie ice cream.",Justin Woolverton,Los Angeles,CA,halotop.com,Halo Top Creamery has sold 50 million pints si...
5,6,Small Business Owners of America,$19.7 M,Financial Services,15.0,2011.0,"19,352%",Provides short-term financing to businesses an...,James Moore,Columbus,OH,sbooa.com,Small Business Owners of America started in 20...
6,7,AutomotiveMastermind,$23.2 M,Software,102.0,2012.0,"17,675%",Develops predictive analytics and marketing au...,Marco Schnabl,New York City,NY,automotivemastermind.com,"AutomotiveMastermind, based in New York City, ..."
7,8,Liftoff,$59.6 M,Advertising & Marketing,NaN,2012.0,"16,981%",A mobile marketing platform on which clients p...,Mark Ellis,Palo Alto,CA,liftoff.io,Liftoff is the rare mobile marketing success t...
8,9,Greenspire,$41.7 M,Energy,150.0,2012.0,"14,429%",Offers energy-related programs to help residen...,David Murray,Los Angeles,CA,greenspirehome.com,Los Angeles-based Greenspire knows that having...
9,10,FormulaFolio Investments,$17.2 M,Financial Services,43.0,2011.0,"13,927%","Manages money serving investors, nonprofits an...",Jason Wenk,Grand Rapids,MI,formulafolios.com,FormulaFolio Investments is an algorithm-based...

In [63]:
analysis_df = inc_df[['Rank_2017', 'Company_Name', 'Revenue_2016', 'Industry', 'Employees', 'Founded', 'Growth_3_yrs', 'City', 'State']]

In [64]:
analysis_df.head(10)

,Rank_2017,Company_Name,Revenue_2016,Industry,Employees,Founded,Growth_3_yrs,City,State
0,1,Skillz,$54.2 M,Software,58.0,2012.0,"50,059%",San Francisco,CA
1,2,EnviroSolar Power,$37.4 M,Energy,85.0,2012.0,"36,065%",Fort Worth,TX
2,3,Gametime,$48.8 M,Consumer Products & Services,75.0,2013.0,"34,021%",San Francisco,CA
3,4,Club Pilates Franchise,$26.8 M,Consumer Products & Services,31.0,2007.0,"21,319%",Costa Mesa,CA
4,5,Halo Top Creamery,$49.1 M,Food & Beverage,10.0,2012.0,"20,944%",Los Angeles,CA
5,6,Small Business Owners of America,$19.7 M,Financial Services,15.0,2011.0,"19,352%",Columbus,OH
6,7,AutomotiveMastermind,$23.2 M,Software,102.0,2012.0,"17,675%",New York City,NY
7,8,Liftoff,$59.6 M,Advertising & Marketing,NaN,2012.0,"16,981%",Palo Alto,CA
8,9,Greenspire,$41.7 M,Energy,150.0,2012.0,"14,429%",Los Angeles,CA
9,10,FormulaFolio Investments,$17.2 M,Financial Services,43.0,2011.0,"13,927%",Grand Rapids,MI

In [65]:
analysis_df.columns = ['rank','name','revenue','industry','employees','founded','growth','city','state']
analysis_df.head(2)

,rank,name,revenue,industry,employees,founded,growth,city,state
0,1,Skillz,$54.2 M,Software,58.0,2012.0,"50,059%",San Francisco,CA
1,2,EnviroSolar Power,$37.4 M,Energy,85.0,2012.0,"36,065%",Fort Worth,TX

In [66]:
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 9 columns):
rank         4997 non-null int64
name         4997 non-null object
revenue      4997 non-null object
industry     4993 non-null object
employees    4861 non-null float64
founded      4994 non-null float64
growth       4997 non-null object
city         4996 non-null object
state        4997 non-null object
dtypes: float64(2), int64(1), object(6)
memory usage: 351.4+ KB

In [67]:
analysis_df['industry'].value_counts()

IT Services                     598
Advertising & Marketing         493
Business Products & Services    474
Health                          395
Software                        328
Construction                    301
Financial Services              262
Government Services             240
Consumer Products & Services    239
Real Estate                     197
Human Resources                 186
Retail                          168
Logistics & Transportation      149
Manufacturing                   145
Food & Beverage                 137
Energy                           91
Insurance                        89
Telecommunications               86
Education                        74
Security                         68
Engineering                      67
Media                            65
Travel & Hospitality             63
Environmental Services           42
Computer Hardware                36
Name: industry, dtype: int64

In [68]:
analysis_df.groupby('industry').describe()

                             employees                                         \
                                 count         mean           std  min    25%
industry
Advertising & Marketing          465.0    65.503226     88.463053  1.0  20.00
Business Products & Services     463.0   272.166307   1875.947653  1.0  20.00
Computer Hardware                 35.0    52.257143     75.076958  4.0  15.50
Construction                     297.0    88.548822    154.630876  2.0  19.00
Consumer Products & Services     236.0   114.576271    367.425961  2.0  15.00
Education                         73.0   529.082192   2859.930893  3.0  18.00
Energy                            89.0   130.112360    255.302781  4.0  28.00
Engineering                       66.0   139.000000    193.745749  2.0  31.25
Environmental Services            41.0   120.463415    192.699130  7.0  22.00
Financial Services               259.0   274.274131    699.960717  2.0  25.00
Food & Beverage                  137.0   384.197080   1103.789474  3.0  23.00
Government Services              236.0   187.775424    480.184695  6.0  42.00
Health                           382.0   360.934555   1297.360744  3.0  32.00
Human Resources                  181.0  1022.331492   4902.726431  6.0  28.00
IT Services                      573.0   213.652705   1575.971447  3.0  27.00
Insurance                         88.0   221.568182    497.096970  5.0  24.25
Logistics & Transportation       144.0   228.194444    655.143024  1.0  20.75
Manufacturing                    144.0   162.416667    405.857057  4.0  25.00
Media                             63.0   145.253968    635.106213  3.0  17.50
Real Estate                      195.0   122.661538    217.656469  1.0  17.00
Retail                           168.0   165.017857    652.942978  1.0  13.00
Security                          67.0  2395.746269  17081.125417  3.0  38.50
Software                         312.0   124.820513    207.115374  0.0  31.00
Telecommunications                83.0   171.144578    627.746728  2.0  21.50
Travel & Hospitality              61.0   359.803279   1547.730175  2.0  18.00

                                                     founded               \
                               50%     75%       max   count         mean
industry
Advertising & Marketing       38.0   76.00     804.0   493.0  2005.247465
Business Products & Services  40.0  120.00   38000.0   474.0  2000.964135
Computer Hardware             33.0   54.00     419.0    36.0  2005.555556
Construction                  39.0   91.00    1400.0   301.0  1999.438538
Consumer Products & Services  33.5   75.25    4374.0   239.0  2004.305439
Education                     38.0  108.00   24047.0    74.0  2004.189189
Energy                        54.0  117.00    1830.0    91.0  2005.351648
Engineering                   60.5  177.00    1200.0    67.0  1996.417910
Environmental Services        50.0  111.00    1000.0    42.0  1999.333333
Financial Services            64.0  209.50    5618.0   261.0  2002.720307
Food & Beverage               54.0  244.00    9584.0   137.0  2003.810219
Government Services           87.0  168.25    5000.0   240.0  2004.741667
Health                        79.0  243.75   18314.0   394.0  2004.601523
Human Resources               74.0  205.00   53557.0   186.0  2002.650538
IT Services                   54.0  120.00   36000.0   598.0  2004.342809
Insurance                     54.0  167.50    2947.0    88.0  1999.886364
Logistics & Transportation    44.0  103.50    5900.0   149.0  2003.570470
Manufacturing                 50.0  126.25    3400.0   145.0  1993.917241
Media                         34.0   79.00    5000.0    65.0  2005.461538
Real Estate                   38.0  106.00    1338.0   197.0  2005.055838
Retail                        26.0   80.00    7200.0   168.0  2005.244048
Security                      89.0  211.00  140000.0    68.0  2004.470588
Software                      57.0  125.50    2000.0   328.0  2005.179878
Telecommunications            42.0  108.00    5559.0    86.0  2001.313953
Travel & Hospitality          42.0  150.00   11600.0    63.0  2005.015873

                               ...                     rank               \
                               ...       75%     max  count         mean
industry                       ...
Advertising & Marketing        ...    2010.0  2013.0  493.0  2435.438134
Business Products & Services   ...    2010.0  2013.0  474.0  2630.329114
Computer Hardware              ...    2011.0  2013.0   36.0  2290.944444
Construction                   ...    2010.0  2013.0  301.0  2557.209302
Consumer Products & Services   ...    2011.0  2013.0  239.0  2294.288703
Education                      ...    2009.0  2012.0   74.0  2246.648649
Energy                         ...    2011.0  2013.0   91.0  1793.659341
Engineering                    ...    2007.5  2013.0   67.0  2966.313433
Environmental Services         ...    2008.0  2012.0   42.0  2712.047619
Financial Services             ...    2009.0  2013.0  262.0  2556.137405
Food & Beverage                ...    2010.0  2013.0  137.0  2225.890511
Government Services            ...    2009.0  2013.0  240.0  2140.879167
Health                         ...    2010.0  2013.0  395.0  2449.263291
Human Resources                ...    2009.0  2013.0  186.0  2796.021505
IT Services                    ...    2009.0  2013.0  598.0  2739.772575
Insurance                      ...    2008.0  2013.0   89.0  2713.191011
Logistics & Transportation     ...    2011.0  2013.0  149.0  2396.993289
Manufacturing                  ...    2007.0  2013.0  145.0  3222.862069
Media                          ...    2011.0  2013.0   65.0  2360.830769
Real Estate                    ...    2010.0  2013.0  197.0  2301.573604
Retail                         ...    2011.0  2013.0  168.0  2092.851190
Security                       ...    2009.0  2013.0   68.0  2409.102941
Software                       ...    2010.0  2013.0  328.0  2336.963415
Telecommunications             ...    2006.0  2013.0   86.0  3094.383721
Travel & Hospitality           ...    2011.0  2013.0   63.0  2509.730159

                                                                            \
                                      std    min      25%     50%      75%
industry
Advertising & Marketing       1422.639218    8.0  1194.00  2382.0  3606.00
Business Products & Services  1466.450519   22.0  1426.25  2684.0  3965.25
Computer Hardware             1434.654462  249.0  1116.25  2051.0  3479.50
Construction                  1389.083218   42.0  1357.00  2522.0  3725.00
Consumer Products & Services  1469.953325    3.0  1057.50  2158.0  3534.00
Education                     1411.302618   78.0   987.25  2291.5  3447.75
Energy                        1509.215206    2.0   545.50  1430.0  2887.00
Engineering                   1349.171128  199.0  1814.50  3256.0  4199.50
Environmental Services        1451.249940  456.0  1486.75  2579.5  3894.75
Financial Services            1439.183265    6.0  1420.50  2512.5  3821.00
Food & Beverage               1492.744899    5.0   824.00  2153.0  3532.00
Government Services           1400.547707   20.0   968.75  1908.0  3282.25
Health                        1420.151299   13.0  1264.50  2450.0  3585.00
Human Resources               1341.959024   37.0  1767.50  3084.5  3825.75
IT Services                   1380.445018   30.0  1579.75  2940.5  3934.25
Insurance                     1340.819872   19.0  1692.00  2743.0  3826.00
Logistics & Transportation    1496.467762   12.0  1065.00  2524.0  3557.00
Manufacturing                 1420.431882   51.0  2263.00  3444.0  4441.00
Media                         1548.069994   25.0   907.00  2249.0  3648.00
Real Estate                   1348.742862   31.0  1279.00  2090.0  3507.00
Retail                        1488.026119   18.0   704.50  1901.5  3178.50
Security                      1346.305161  169.0  1260.00  2358.5  3489.25
Software                      1431.143293    1.0  1098.00  2241.0  3620.75
Telecommunications            1320.535552  201.0  2164.50  3317.5  4179.00
Travel & Hospitality          1541.859217   63.0  1156.00  2511.0  3894.00


                                 max
industry
Advertising & Marketing       4989.0
Business Products & Services  4991.0
Computer Hardware             4871.0
Construction                  4951.0
Consumer Products & Services  4987.0
Education                     4956.0
Energy                        4932.0
Engineering                   4941.0
Environmental Services        4918.0
Financial Services            4984.0
Food & Beverage               4992.0
Government Services           5000.0
Health                        4996.0
Human Resources               4935.0
IT Services                   4988.0
Insurance                     4839.0
Logistics & Transportation    4999.0
Manufacturing                 4995.0
Media                         4960.0
Real Estate                   4978.0
Retail                        4998.0
Security                      4765.0
Software                      4997.0
Telecommunications            4979.0
Travel & Hospitality          4976.0

[25 rows x 24 columns]

In [69]:
# check if all 'revenue' values are in M (million)
analysis_df['revenue'].apply(lambda x: x[-1]).value_counts()

M    4997
Name: revenue, dtype: int64

In [70]:
# check if all 'revenue' values are in $
analysis_df['revenue'].apply(lambda x: x[0]).value_counts()

$    4997
Name: revenue, dtype: int64

In [71]:
#check if there is space between $ sign and amount for any row
analysis_df['revenue'].apply(lambda x: x[1]).value_counts()

1    1138
2    1015
3     738
4     566
5     445
6     348
7     311
8     256
9     180
Name: revenue, dtype: int64

In [72]:
# and there sum is equal to total number of rows
analysis_df['revenue'].apply(lambda x: x[1]).value_counts().values.sum()

4997

In [73]:
# check if all row values for 'revenue' has space between amount and 'M'
analysis_df['revenue'].apply(lambda x: x[-2]).value_counts()

     4997
Name: revenue, dtype: int64

In [74]:
# change 'revenue' column format to numerical values by removing $ and M
analysis_df.loc[:,('revenue')] = analysis_df['revenue'].apply(lambda x: x[1:-2]).values

/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [75]:
analysis_df.head(10)

,rank,name,revenue,industry,employees,founded,growth,city,state
0,1,Skillz,54.2,Software,58.0,2012.0,"50,059%",San Francisco,CA
1,2,EnviroSolar Power,37.4,Energy,85.0,2012.0,"36,065%",Fort Worth,TX
2,3,Gametime,48.8,Consumer Products & Services,75.0,2013.0,"34,021%",San Francisco,CA
3,4,Club Pilates Franchise,26.8,Consumer Products & Services,31.0,2007.0,"21,319%",Costa Mesa,CA
4,5,Halo Top Creamery,49.1,Food & Beverage,10.0,2012.0,"20,944%",Los Angeles,CA
5,6,Small Business Owners of America,19.7,Financial Services,15.0,2011.0,"19,352%",Columbus,OH
6,7,AutomotiveMastermind,23.2,Software,102.0,2012.0,"17,675%",New York City,NY
7,8,Liftoff,59.6,Advertising & Marketing,NaN,2012.0,"16,981%",Palo Alto,CA
8,9,Greenspire,41.7,Energy,150.0,2012.0,"14,429%",Los Angeles,CA
9,10,FormulaFolio Investments,17.2,Financial Services,43.0,2011.0,"13,927%",Grand Rapids,MI

In [76]:
analysis_df['city'].value_counts()

New York City        162
Atlanta              107
Chicago              107
Houston               85
Austin                83
San Diego             70
Dallas                56
San Francisco         54
Portland              47
Denver                45
Irvine                44
Seattle               43
Tampa                 43
Los Angeles           42
Washington            42
Boston                41
Phoenix               40
Orlando               36
Indianapolis          30
McLean                30
Arlington             28
Alpharetta            27
Columbus              27
Charlotte             27
Philadelphia          26
Minneapolis           26
Nashville             25
Cincinnati            25
Scottsdale            25
Plano                 24
                    ...
tempe                  1
Coralville             1
Dickinson              1
Kenilworth             1
Nampa                  1
North Brunswick        1
Port Vincent           1
White                  1
Winston Salem          1
Topeka                 1
Warren                 1
Conyers                1
Woodside               1
Gulf Breeze            1
West New York          1
Ponte Vedra Beach      1
San Bernardino         1
Clinton                1
Collinsville           1
Tea                    1
STILLWATER             1
Schnecksville          1
Acton                  1
Bellaire               1
North Fort Myers       1
Acworth                1
Crofton                1
Romeoville             1
Mckees Rocks           1
Millbury               1
Name: city, Length: 1406, dtype: int64

In [82]:
analysis_df['revenue']

0        54.2
1        37.4
2        48.8
3        26.8
4        49.1
5        19.7
6        23.2
7        59.6
8        41.7
9        17.2
10       13.8
11       13.1
12       24.4
13       25.8
14       28.3
15       59.2
16       46.5
17       15.7
18       16.8
19       32.9
20       12.1
21       29.3
22       59.3
23       65.7
24       20.5
25       19.2
26       29.8
27       11.4
28       15.1
29       19.1
        ...
4967      9.2
4968     10.3
4969        4
4970     31.3
4971       10
4972        6
4973    159.5
4974      7.7
4975     10.7
4976      4.5
4977     16.3
4978      2.8
4979    233.4
4980     88.8
4981     88.3
4982     17.7
4983       15
4984     12.8
4985      6.4
4986     10.6
4987    380.5
4988       23
4989     18.5
4990     18.7
4991       31
4992      4.9
4993      6.2
4994    639.1
4995    232.1
4996       30
Name: revenue, Length: 4997, dtype: object

In [87]:
analysis_df.loc[:,('revenue')] = analysis_df['revenue'].apply(pd.to_numeric)

/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [94]:
analysis_df['revenue'][:10]

0    54.2
1    37.4
2    48.8
3    26.8
4    49.1
5    19.7
6    23.2
7    59.6
8    41.7
9    17.2
Name: revenue, dtype: float64

In [95]:
analysis_df.groupby('industry').describe()['revenue']

,count,mean,std,min,25%,50%,75%,max
industry,,,,,,,,
Advertising & Marketing,493.0,17.898783,35.214783,2.0,3.600,6.70,15.200,514.3
Business Products & Services,474.0,40.125316,153.312802,2.0,4.225,8.20,22.700,1860.0
Computer Hardware,36.0,28.805556,46.864272,2.1,7.150,17.40,33.175,276.1
Construction,301.0,43.220266,122.608354,2.0,5.100,11.40,28.700,1310.7
Consumer Products & Services,239.0,51.448954,248.667479,1.7,4.200,8.70,24.850,3034.7
Education,74.0,18.682432,33.681820,2.0,2.800,5.60,14.475,181.0
Energy,91.0,45.269231,82.487891,2.0,9.100,20.40,43.950,479.0
Engineering,67.0,23.829851,33.897166,2.1,5.600,12.40,29.300,207.2
Environmental Services,42.0,24.854762,45.707726,2.1,4.200,8.10,25.600,272.7
Financial Services,262.0,164.793511,1610.257581,1.9,5.700,15.35,55.800,26011.7
Food & Beverage,137.0,37.375182,70.207767,2.0,5.700,12.60,34.800,565.6
Government Services,240.0,45.149167,225.562540,1.9,7.275,15.05,33.375,3429.5
Health,395.0,62.199494,268.644821,2.0,6.250,15.40,46.250,4730.2
Human Resources,186.0,64.627419,192.341138,2.0,5.100,10.95,37.150,1890.1
IT Services,598.0,25.695151,78.620986,2.0,4.400,8.75,21.875,1676.7
Insurance,89.0,66.930337,120.716991,2.0,6.500,16.60,71.800,640.4
Logistics & Transportation,149.0,86.126846,322.331085,2.0,6.000,13.10,46.900,2692.7
Manufacturing,145.0,41.333103,84.486863,1.7,5.100,12.80,39.800,628.7
Media,65.0,15.143077,20.066522,2.2,4.500,10.00,18.200,123.6
Real Estate,197.0,31.919797,70.118611,2.1,4.300,8.30,25.500,683.8
Retail,168.0,43.092262,140.300496,2.0,4.450,9.70,27.025,1488.3
Security,68.0,105.476471,478.417730,2.0,4.875,11.20,33.875,3431.6
Software,328.0,17.804573,34.968144,1.7,4.000,7.60,18.425,488.7
Telecommunications,86.0,42.546512,141.142698,2.0,5.125,12.05,30.575,1131.8
Travel & Hospitality,63.0,41.417460,119.607342,2.0,4.500,8.60,25.050,880.4

In [99]:
analysis_df['growth'].apply(lambda x: x[1]).value_counts()

0    563
1    522
2    502
4    475
3    474
5    474
6    442
,    417
7    395
8    367
9    366
Name: growth, dtype: int64

In [104]:
analysis_df.sort_values(by='revenue', ascending=False)

,rank,name,revenue,industry,employees,founded,growth,city,state
4022,4026,Freepoint Commodities,26011.7,Financial Services,329.0,2011.0,70%,Stamford,CT
3515,3519,Prime Therapeutics,4730.2,Health,3649.0,1998.0,88%,Eagan,MN
1240,1242,Allied Universal,3431.6,Security,140000.0,1965.0,329%,Santa Ana,CA
3251,3255,Carahsoft Technology,3429.5,Government Services,655.0,2004.0,99%,Reston,VA
2909,2913,DriveTime,3034.7,Consumer Products & Services,4374.0,2002.0,116%,Tempe,AZ
3645,3649,ARMADA,2692.7,Logistics & Transportation,459.0,1890.0,84%,Pittsburgh,PA
4912,4916,Total Quality Logistics,2321.1,Logistics & Transportation,3001.0,1997.0,43%,Cincinnati,OH
3893,3897,Optiv Security,2045.9,Security,1710.0,1996.0,74%,Denver,CO
540,542,Pinnacle Group,1890.1,Human Resources,1268.0,1996.0,832%,Dallas,TX
4879,4883,Morgan Lewis,1860.0,Business Products & Services,1844.0,1873.0,44%,New York City,NY
2949,2953,SRS Distribution,1778.8,Consumer Products & Services,2593.0,2008.0,114%,McKinney,TX
3667,3671,Insight Global,1676.7,IT Services,36000.0,2001.0,83%,Atlanta,GA
2556,2558,Transportation Insight,1638.3,Logistics & Transportation,421.0,1999.0,138%,Hickory,NC
4770,4774,Cellular Sales of Knoxville,1488.3,Retail,7200.0,1993.0,47%,Knoxville,TN
4695,4699,Ropes & Gray,1485.5,Business Products & Services,1161.0,1865.0,49%,Boston,MA
865,867,Jeunesse Global,1335.9,Consumer Products & Services,850.0,2009.0,518%,Lake Mary,FL
4728,4732,Shawmut Design and Construction,1310.7,Construction,1237.0,1982.0,48%,Boston,MA
1416,1418,loanDepot,1296.5,Financial Services,5618.0,2010.0,286%,Foothill Ranch,CA
2677,2680,Avella Specialty Pharmacy,1293.9,Health,510.0,1996.0,129%,Phoenix,AZ
4524,4528,G&A Partners,1278.6,Human Resources,271.0,1995.0,54%,Houston,TX
4445,4449,Sutherland Global Services,1205.0,Business Products & Services,38000.0,1986.0,56%,Pittsford,NY
4255,4259,Signature HealthCARE,1190.4,Health,18314.0,2007.0,62%,Louisville,KY
1840,1842,Freedom Mortgage,1140.9,Financial Services,5416.0,1990.0,209%,Mount Laurel,NJ
812,814,ABC Phones of North Carolina,1131.8,Telecommunications,5559.0,1996.0,556%,Greenville,NC
4050,4054,Heartland Dental,1124.6,Business Products & Services,9452.0,1997.0,69%,Effingham,IL
2711,2715,ARCO Construction Company,1096.0,Construction,512.0,1992.0,127%,St. Louis,MO
4069,4073,Pacific Dental Services,1046.6,Health,7939.0,1994.0,68%,Irvine,CA
4033,4037,Prestige Employee Administrators,996.7,Human Resources,11792.0,1998.0,69%,Melville,NY
4866,4870,Cooley,974.0,Business Products & Services,854.0,1920.0,45%,New York City,NY
3094,3098,Isagenix,924.3,Health,675.0,2002.0,106%,Gilbert,AZ
...,...,...,...,...,...,...,...,...,...
1386,1388,CFO Alliance,2.0,Business Products & Services,12.0,2008.0,293%,Tampa,FL
3830,3834,SCI,2.0,Telecommunications,15.0,1992.0,76%,Cheektowaga,NY
870,872,TruStar Talent Solutions,2.0,Human Resources,22.0,2008.0,514%,West Chester,OH
4236,4240,Hampton Creative,2.0,Advertising & Marketing,13.0,2002.0,62%,Tulsa,OK
4419,4423,IN10SE Productions,2.0,Consumer Products & Services,2.0,2008.0,57%,Ft Wayne,IN
4318,4322,PeerSource,2.0,IT Services,11.0,2011.0,60%,Englewood,CO
3003,3007,Kopp Consulting,2.0,Business Products & Services,23.0,1999.0,110%,Bedminster,NJ
4240,4244,Stratus Interactive,2.0,Advertising & Marketing,18.0,2006.0,62%,West Chester,PA
1230,1232,Amicon Management,2.0,Construction,15.0,1996.0,331%,Miami,FL
260,262,Adwizar,2.0,Advertising & Marketing,15.0,2012.0,"1,656%",Rancho Cucamonga,CA
337,339,Waterbottles.com,2.0,Business Products & Services,5.0,2011.0,"1,312%",Glendora,CA
2484,2486,New York Dynamic Neuromuscular Rehabilitation ...,2.0,Health,11.0,2010.0,143%,New York City,NY
1663,1665,Visiture,2.0,Advertising & Marketing,20.0,2008.0,235%,Charleston,SC
3258,3262,Treeline,2.0,Business Products & Services,NaN,2001.0,98%,Wakefield,MA
849,851,Blueprint Summer Programs,2.0,Education,13.0,2007.0,529%,Asheville,NC
553,555,B'more Organic,2.0,Food & Beverage,6.0,2011.0,810%,Baltimore,MD
4384,4388,JMF Solutions,2.0,Telecommunications,28.0,2005.0,58%,Daphne,AL
1255,1257,The Cobalt Companies,2.0,Construction,2.0,2002.0,325%,Austin,TX
3688,3692,Evergreen Escapes / EG-X,2.0,Travel & Hospitality,30.0,2006.0,82%,Seattle,WA
4009,4013,Blue Magnet Interactive Marketing & Media,2.0,Advertising & Marketing,25.0,2007.0,70%,Chicago,IL
1262,1264,Alarm Grid,2.0,Security,8.0,2012.0,324%,Lighthouse Point,FL
234,236,Facility Innovations Group,2.0,Business Products & Services,28.0,2013.0,"1,809%",Austin,TX
2531,2533,United Mortgage,2.0,Financial Services,14.0,2007.0,139%,Overland Park,KS
232,234,GRA CPA,2.0,Financial Services,9.0,2010.0,"1,829%",Orlando,FL
3287,3291,TheLions,2.0,Human Resources,20.0,2010.0,97%,San Francisco,CA
2387,2389,PinPoint Collateral,1.9,Financial Services,6.0,2012.0,152%,Pasadena,CA
655,657,World Services,1.9,Government Services,8.0,2010.0,694%,Alexandria,VA
1349,1351,MavTel Global Solutions,1.7,Manufacturing,16.0,2013.0,302%,Dallas,TX
4720,4724,Weiss & Associates,1.7,Consumer Products & Services,9.0,2001.0,48%,New York City,NY
1470,1472,kordinator,1.7,Software,11.0,2010.0,276%,Chicago,IL

In [110]:
analysis_df.loc[:,('growth')] = analysis_df['growth'].apply(lambda x: "".join(x[:-1].split(","))).values

/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [119]:
analysis_df.loc[:,('growth')] = analysis_df['growth'].apply(pd.to_numeric)

/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [120]:
analysis_df['growth'].head()

0    50059
1    36065
2    34021
3    21319
4    20944
Name: growth, dtype: int64

In [121]:
analysis_df.head()

,rank,name,revenue,industry,employees,founded,growth,city,state
0,1,Skillz,54.2,Software,58.0,2012.0,50059,San Francisco,CA
1,2,EnviroSolar Power,37.4,Energy,85.0,2012.0,36065,Fort Worth,TX
2,3,Gametime,48.8,Consumer Products & Services,75.0,2013.0,34021,San Francisco,CA
3,4,Club Pilates Franchise,26.8,Consumer Products & Services,31.0,2007.0,21319,Costa Mesa,CA
4,5,Halo Top Creamery,49.1,Food & Beverage,10.0,2012.0,20944,Los Angeles,CA

In [132]:
analysis_df[pd.isnull(analysis_df['founded'])]

,rank,name,revenue,industry,employees,founded,growth,city,state
155,156,"FYZICAL Therapy & Balance Centers (Sarasota, FL)",7.8,Health,12.0,NaN,2557,Sarasota,FL
4114,4118,Southwest Capital Bank,19.0,Financial Services,100.0,NaN,66,Albuquerque,NM
4239,4243,Morris & Garritano Insurance Agency,17.2,Insurance,116.0,NaN,62,San Luis Obispo,CA

In [141]:
analysis_df.groupby('industry').describe()[['revenue','growth']]

                             revenue                                       \
                               count        mean          std  min    25%
industry
Advertising & Marketing        493.0   17.898783    35.214783  2.0  3.600
Business Products & Services   474.0   40.125316   153.312802  2.0  4.225
Computer Hardware               36.0   28.805556    46.864272  2.1  7.150
Construction                   301.0   43.220266   122.608354  2.0  5.100
Consumer Products & Services   239.0   51.448954   248.667479  1.7  4.200
Education                       74.0   18.682432    33.681820  2.0  2.800
Energy                          91.0   45.269231    82.487891  2.0  9.100
Engineering                     67.0   23.829851    33.897166  2.1  5.600
Environmental Services          42.0   24.854762    45.707726  2.1  4.200
Financial Services             262.0  164.793511  1610.257581  1.9  5.700
Food & Beverage                137.0   37.375182    70.207767  2.0  5.700
Government Services            240.0   45.149167   225.562540  1.9  7.275
Health                         395.0   62.199494   268.644821  2.0  6.250
Human Resources                186.0   64.627419   192.341138  2.0  5.100
IT Services                    598.0   25.695151    78.620986  2.0  4.400
Insurance                       89.0   66.930337   120.716991  2.0  6.500
Logistics & Transportation     149.0   86.126846   322.331085  2.0  6.000
Manufacturing                  145.0   41.333103    84.486863  1.7  5.100
Media                           65.0   15.143077    20.066522  2.2  4.500
Real Estate                    197.0   31.919797    70.118611  2.1  4.300
Retail                         168.0   43.092262   140.300496  2.0  4.450
Security                        68.0  105.476471   478.417730  2.0  4.875
Software                       328.0   17.804573    34.968144  1.7  4.000
Telecommunications              86.0   42.546512   141.142698  2.0  5.125
Travel & Hospitality            63.0   41.417460   119.607342  2.0  4.500

                                                     growth               \
                                50%     75%      max  count         mean
industry
Advertising & Marketing        6.70  15.200    514.3  493.0   454.507099
Business Products & Services   8.20  22.700   1860.0  474.0   431.320675
Computer Hardware             17.40  33.175    276.1   36.0   342.638889
Construction                  11.40  28.700   1310.7  301.0   361.554817
Consumer Products & Services   8.70  24.850   3034.7  239.0   696.958159
Education                      5.60  14.475    181.0   74.0   443.108108
Energy                        20.40  43.950    479.0   91.0  1562.450549
Engineering                   12.40  29.300    207.2   67.0   206.149254
Environmental Services         8.10  25.600    272.7   42.0   220.928571
Financial Services            15.35  55.800  26011.7  262.0   527.958015
Food & Beverage               12.60  34.800    565.6  137.0   743.364964
Government Services           15.05  33.375   3429.5  240.0   649.229167
Health                        15.40  46.250   4730.2  395.0   440.878481
Human Resources               10.95  37.150   1890.1  186.0   314.161290
IT Services                    8.75  21.875   1676.7  598.0   306.220736
Insurance                     16.60  71.800    640.4   89.0   397.561798
Logistics & Transportation    13.10  46.900   2692.7  149.0   653.550336
Manufacturing                 12.80  39.800    628.7  145.0   248.000000
Media                         10.00  18.200    123.6   65.0   708.046154
Real Estate                    8.30  25.500    683.8  197.0   398.142132
Retail                         9.70  27.025   1488.3  168.0   672.976190
Security                      11.20  33.875   3431.6   68.0   328.602941
Software                       7.60  18.425    488.7  328.0   625.692073
Telecommunications            12.05  30.575   1131.8   86.0   202.406977
Travel & Hospitality           8.60  25.050    880.4   63.0   402.476190

                                                                        \
                                      std   min     25%    50%     75%
industry
Advertising & Marketing       1282.605860  41.0   85.00  152.0  346.00
Business Products & Services  1086.115869  41.0   72.00  129.0  284.50
Computer Hardware              393.042139  44.0   89.75  183.5  376.75
Construction                   725.911726  42.0   80.00  140.0  300.00
Consumer Products & Services  2708.965457  41.0   87.50  169.0  401.00
Education                      748.842258  42.0   90.50  158.5  437.75
Energy                        4376.897271  43.0  117.50  284.0  827.50
Engineering                    314.386572  42.0   63.50   99.0  213.00
Environmental Services         226.399969  43.0   74.25  136.5  272.00
Financial Services            1771.956047  41.0   76.50  141.0  285.75
Food & Beverage               2271.434675  40.0   87.00  169.0  549.00
Government Services           1428.438742  40.0   97.50  201.0  447.50
Health                        1160.531567  40.0   85.50  146.0  323.50
Human Resources                732.753058  42.0   76.25  107.0  220.00
IT Services                    677.889261  41.0   73.00  114.0  249.75
Insurance                     1265.280107  45.0   77.00  125.0  231.00
Logistics & Transportation    1626.461324  40.0   87.00  140.0  397.00
Manufacturing                  619.128218  40.0   57.00   91.0  161.00
Media                         1717.138812  42.0   84.00  162.0  487.00
Real Estate                    852.537485  41.0   89.00  176.0  319.00
Retail                        1410.209353  40.0  102.25  201.5  646.25
Security                       486.793135  47.0   89.75  153.0  325.00
Software                      3003.612171  40.0   84.75  163.0  383.75
Telecommunications             341.686694  41.0   64.25   96.5  168.75
Travel & Hospitality           773.013935  41.0   74.50  141.0  360.00


                                  max
industry
Advertising & Marketing       16981.0
Business Products & Services   9935.0
Computer Hardware              1720.0
Construction                   6611.0
Consumer Products & Services  34021.0
Education                      4654.0
Energy                        36065.0
Engineering                    2196.0
Environmental Services          963.0
Financial Services            19352.0
Food & Beverage               20944.0
Government Services           10999.0
Health                        13462.0
Human Resources                6885.0
IT Services                    9114.0
Insurance                     11369.0
Logistics & Transportation    13666.0
Manufacturing                  6062.0
Media                          9396.0
Real Estate                    8829.0
Retail                        12327.0
Security                       2463.0
Software                      50059.0
Telecommunications             2123.0
Travel & Hospitality           5379.0

In [142]:
analysis_df.to_csv('inc_cleaned_data.csv', index=False, sep='|')

In [143]:
dfs = pd.read_csv('inc_cleaned_data.csv', sep='|')

In [145]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 9 columns):
rank         4997 non-null int64
name         4997 non-null object
revenue      4997 non-null float64
industry     4993 non-null object
employees    4861 non-null float64
founded      4994 non-null float64
growth       4997 non-null int64
city         4996 non-null object
state        4997 non-null object
dtypes: float64(3), int64(2), object(4)
memory usage: 351.4+ KB

In [146]:
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 9 columns):
rank         4997 non-null int64
name         4997 non-null object
revenue      4997 non-null float64
industry     4993 non-null object
employees    4861 non-null float64
founded      4994 non-null float64
growth       4997 non-null int64
city         4996 non-null object
state        4997 non-null object
dtypes: float64(3), int64(2), object(4)
memory usage: 351.4+ KB